stages:
 - build

Ubuntu-OptionalDeps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DPYGEMS_OPTIONALS_AS_REQUIRED=ON"
  - export BUILD_GENERATOR="Ninja"
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

Ubuntu-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - export BUILD_GENERATOR="Ninja"
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

Ubuntu-Subproject-master:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - export BUILD_GENERATOR="Ninja"
  - export GITHUB_MIRROR_URL="git@github.com:gmrvvis/pygems"
  - bash .gitlab-ci.sh
 only:
  - master
 tags:
  - ubuntu

Win7:
 stage: build
 script:
  - call %ENVFILESDIR%\Boost-1.72-vs14-x64.bat
  - call %ENVFILESDIR%\eigen-3.1.2-vs12-x64.bat
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - set PATH=%PATH%;"c:\Program Files\Git\bin"
  - bash.exe --login .gitlab-ci.sh
 tags:
  - win7
